	
pythia: pythia.cpp
	g++ -I/home/isidiras/pythia/pythia8307/include `root-config --cflags` $@.cpp -o $@ -lpythia8 -L/home/isidiras/pythia/pythia8307/lib `root-config --glibs`

CharmDeltaPhi: CharmDeltaPhi.cpp
	g++ -I/home/isidiras/pythia/pythia8307/include `root-config --cflags` $@.cpp -o $@ -lpythia8 -L/home/isidiras/pythia/pythia8307/lib `root-config --glibs`
	
ccbarcorrelations: ccbarcorrelations.cpp
	g++ -I/home/isidiras/pythia/pythia8307/include `root-config --cflags` $@.cpp -o $@ -lpythia8 -L/home/isidiras/pythia/pythia8307/lib `root-config --glibs`	
